site_name: Feed Kit
pages:
- Home: 'index.md'
- FeedKit Module: 'FeedKit.md'
- Classes: [
{FeedKit.Feed: 'FeedKit.Feed.md'},
{FeedKit.Entry: 'FeedKit.Entry.md'},
{FeedKit.Attachment: 'FeedKit.Attachment.md'},
{FeedKit.Author: 'FeedKit.Author.md'}
]
- Interfaces: [
{FeedKit.Engine: 'FeedKit.Engine.md'}
]
theme: mkdocs